dist: trusty
language: node_js
sudo: required
env:
- BUILD_LIBRDKAFKA="1"
- BUILD_LIBRDKAFKA="0"
node_js:
- '4'
- '6'
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- echo "deb http://archive.ubuntu.com/ubuntu trusty universe" | sudo tee /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get install -y librdkafka-dev=0.9.1-1
- docker-compose up -d
script:
- make lint
- make test
- make e2e
# after_success:
# - make docs
# - echo "Disallow: /" >> docs/robots.txt
