dist: trusty
language: node_js
sudo: required
env:
- BUILD_LIBRDKAFKA="1"
- BUILD_LIBRDKAFKA="0"
node_js:
- '4'
- '6'
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- sudo add-apt-repository universe
- sudo apt-get -qq update
- sudo apt-get install -y librdkafka-dev
- docker-compose up -d
script:
- make lint
- make test
- make e2e
# after_success:
# - make docs
# - echo "Disallow: /" >> docs/robots.txt
